"""Deterministic `dateLabel` formatting.

The outward `dateLabel` is always generated by the backend from
`start_date`/`end_date` (`trip_info.date_label` is only a model hint). Examples
(《数据结构与通信接口规范》): "2026.7.9-2026.7.12", "2025.08".
"""

from __future__ import annotations


def _parse(date_str: str | None) -> tuple[int, int | None, int | None] | None:
    """Parse `YYYY-MM-DD` or `YYYY-MM` into (year, month?, day?)."""
    if not date_str:
        return None
    parts = date_str.strip().split("-")
    try:
        if len(parts) == 3:
            return int(parts[0]), int(parts[1]), int(parts[2])
        if len(parts) == 2:
            return int(parts[0]), int(parts[1]), None
        if len(parts) == 1 and parts[0]:
            return int(parts[0]), None, None
    except ValueError:
        return None
    return None


def _fmt_full(parsed: tuple[int, int | None, int | None]) -> str:
    year, month, day = parsed
    if month is None:
        return f"{year:04d}"
    if day is None:
        return f"{year:04d}.{month:02d}"
    return f"{year}.{month}.{day}"


def generate_label(start_date: str | None, end_date: str | None) -> str:
    """Build the展示用 date label from start/end dates.

    - same day → "2026.7.9"
    - range    → "2026.7.9-2026.7.12"
    - month-only → "2025.08"
    - missing  → ""
    """
    start = _parse(start_date)
    end = _parse(end_date)

    if start and end:
        left = _fmt_full(start)
        right = _fmt_full(end)
        if left == right:
            return left
        return f"{left}-{right}"
    if start:
        return _fmt_full(start)
    if end:
        return _fmt_full(end)
    return ""
