"""init_schema

Revision ID: a719304102bf
Revises: 
Create Date: 2026-06-12 15:46:31.643828

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a719304102bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_assets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('usage_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path', name='uq_file_assets_relative_path')
    )
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.create_index('idx_file_assets_usage', ['usage_type'], unique=False)
        batch_op.create_index('idx_file_assets_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_assets_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('itinerary_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index('idx_plans_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_plans_user_date', ['user_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('postcard_groups',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postcard_groups', schema=None) as batch_op:
        batch_op.create_index('idx_postcard_groups_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_postcard_groups_user_location', ['user_id', 'location'], unique=False)
        batch_op.create_index(batch_op.f('ix_postcard_groups_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chart_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_reports_user_location', ['user_id', 'location'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('tool_call_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('degraded_to_b', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_call_logs', schema=None) as batch_op:
        batch_op.create_index('idx_tool_call_logs_request', ['request_id'], unique=False)
        batch_op.create_index('idx_tool_call_logs_task', ['task_type'], unique=False)
        batch_op.create_index('idx_tool_call_logs_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_logs_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_call_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_memories',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('memory_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_memories_user_id')
    )
    op.create_table('user_memory_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delta_json', sa.JSON(), nullable=True),
    sa.Column('version_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_memory_events', schema=None) as batch_op:
        batch_op.create_index('idx_user_memory_events_memory', ['memory_id'], unique=False)
        batch_op.create_index('idx_user_memory_events_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_memory_events_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_memory_events_user_id'), ['user_id'], unique=False)

    op.create_table('file_asset_references',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['file_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'owner_type', 'owner_id', 'role', name='uq_far_asset_owner_role')
    )
    with op.batch_alter_table('file_asset_references', schema=None) as batch_op:
        batch_op.create_index('idx_far_asset', ['asset_id'], unique=False)
        batch_op.create_index('idx_far_owner', ['user_id', 'owner_type', 'owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_references_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_references_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_references_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_asset_references_user_id'), ['user_id'], unique=False)

    op.create_table('postcards',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['postcard_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('postcards', schema=None) as batch_op:
        batch_op.create_index('idx_postcards_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_postcards_user_group', ['user_id', 'group_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_postcards_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postcards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postcards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postcards_user_id'))
        batch_op.drop_index(batch_op.f('ix_postcards_group_id'))
        batch_op.drop_index('idx_postcards_user_group')
        batch_op.drop_index('idx_postcards_user_created')

    op.drop_table('postcards')
    with op.batch_alter_table('file_asset_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_asset_references_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_asset_references_owner_type'))
        batch_op.drop_index(batch_op.f('ix_file_asset_references_owner_id'))
        batch_op.drop_index(batch_op.f('ix_file_asset_references_asset_id'))
        batch_op.drop_index('idx_far_owner')
        batch_op.drop_index('idx_far_asset')

    op.drop_table('file_asset_references')
    with op.batch_alter_table('user_memory_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_memory_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_memory_events_memory_id'))
        batch_op.drop_index('idx_user_memory_events_user')
        batch_op.drop_index('idx_user_memory_events_memory')

    op.drop_table('user_memory_events')
    op.drop_table('user_memories')
    with op.batch_alter_table('tool_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_call_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_tool_call_logs_task_type'))
        batch_op.drop_index(batch_op.f('ix_tool_call_logs_request_id'))
        batch_op.drop_index('idx_tool_call_logs_user')
        batch_op.drop_index('idx_tool_call_logs_task')
        batch_op.drop_index('idx_tool_call_logs_request')

    op.drop_table('tool_call_logs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index('idx_reports_user_location')
        batch_op.drop_index('idx_reports_user_created')

    op.drop_table('reports')
    with op.batch_alter_table('postcard_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postcard_groups_user_id'))
        batch_op.drop_index('idx_postcard_groups_user_location')
        batch_op.drop_index('idx_postcard_groups_user_created')

    op.drop_table('postcard_groups')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))
        batch_op.drop_index('idx_plans_user_date')
        batch_op.drop_index('idx_plans_user_created')

    op.drop_table('plans')
    with op.batch_alter_table('file_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_assets_user_id'))
        batch_op.drop_index('idx_file_assets_user_status')
        batch_op.drop_index('idx_file_assets_usage')

    op.drop_table('file_assets')
    # ### end Alembic commands ###
